/* ssip-enums.h
 *
 * Copyright (C) 2013 Brailcom, o.p.s.
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author: Andrei Kholodnyi <andrei.kholodnyi@gmail.com>
 */

#ifndef SSIP_ENUMS_H
#define SSIP_ENUMS_H

G_BEGIN_DECLS

typedef enum {
	SSIP_CMD_SPEAK,
	SSIP_CMD_STOP,
	SSIP_CMD_CANCEL,
	SSIP_CMD_PAUSE,
	SSIP_CMD_RESUME,
	SSIP_CMD_KEY,
	SSIP_CMD_CHAR,
	SSIP_CMD_SOUND_ICON,
	SSIP_CMD_SET,
	SSIP_CMD_GET,
	SSIP_CMD_LIST,
	SSIP_CMD_HISTORY,
	SSIP_CMD_QUIT,
	SSIP_CMD_BYE,
	SSIP_CMD_HELP,
	SSIP_CMD_BLOCK,
} SsipCmd;

typedef enum {
	SSIP_CLIENT_ID_ID,
	SSIP_CLIENT_ID_ALL,
	SSIP_CLIENT_ID_SELF
} SsipClientId;

typedef enum {
	SSIP_SET_PARAM_CLIENT_NAME,
	SSIP_SET_PARAM_OUTPUT_MODULE,
	SSIP_SET_PARAM_AUDIO_MODULE,
	SSIP_SET_PARAM_LANGUAGE,
	SSIP_SET_PARAM_SSML_MODE,
	SSIP_SET_PARAM_PUNCTUATION,
	SSIP_SET_PARAM_SPELLING,
	SSIP_SET_PARAM_CAP_LET_RECOGN,
	SSIP_SET_PARAM_VOICE,
	SSIP_SET_PARAM_SYNTHESIS_VOICE,
	SSIP_SET_PARAM_RATE,
	SSIP_SET_PARAM_PITCH,
	SSIP_SET_PARAM_VOLUME,
	SSIP_SET_PARAM_PAUSE_CONTEXT,
	SSIP_SET_PARAM_HISTORY,
	SSIP_SET_PARAM_DEBUG,
	SSIP_SET_PARAM_NOTIFICATION,
} SsipSetParam;

typedef enum {
	OK_LANGUAGE_SET = 201,
	OK_PRIORITY_SET,
	OK_RATE_SET,
	OK_PITCH_SET,
	OK_PUNCT_MODE_SET,
	OK_CAP_LET_RECOGN_SET,
	OK_SPELLING_SET,
	OK_CLIENT_NAME_SET,
	OK_VOICE_SET,
	OK_STOPPED,
	OK_PAUSED,
	OK_RESUMED,
	OK_CANCELED,
	OK_TABLE_SET,
	OK_OUTPUT_MODULE_SET,
	OK_PAUSE_CONTEXT_SET,
	OK_VOLUME_SET,
	OK_SSML_MODE_SET,
	OK_NOTIFICATION_SET, /* 220 */

	OK_CURSOR_SET_FIRST, /* 221 */
	OK_CURSOR_SET_LAST,
	OK_CURSOR_SET_TO_POSITION,
	OK_CURSOR_MOVED_FORWARD,
	OK_CURSOR_MOVED_BACKWARD,
	OK_MESSAGE_QUEUED,
	OK_SOUND_ICON_QUEUED,
	OK_MESSAGE_CANCELED,  /* 228 */

	OK_RECEIVE_DATA = 231,
	OK_HAPPY_HACKING,

	OK_CLIENTS_LIST_SENT = 240,
	OK_MESSAGES_LIST_SENT,
	OK_LAST_MESSAGE_SAID,
	OK_CURSOR_POSITION_RETURNED,
	OK_TABLE_LIST_SENT,
	OK_CLIENT_ID_SENT,
	OK_MESSAGE_TEXT_SENT,
	OK_HELP_SENT,
	OK_VOICE_LIST_SENT,
	OK_MODULES_LIST_SENT,
	OK_GET_RETURNED, /* 250 */

	OK_INSIDE_BLOCK = 260,
	OK_OUTSIDE_BLOCK,
	OK_DEBUGGING_SET,

	OK_NOT_IMPLEMENTED_DOES_NOTHING = 299,

	ERR_INTERNAL = 300,
	ERR_COULDNT_SET_PRIORITY,
	ERR_COULDNT_SET_LANGUAGE,
	ERR_COULDNT_SET_RATE,
	ERR_COULDNT_SET_PITCH,
	ERR_COULDNT_SET_PUNCT_MODE,
	ERR_COULDNT_SET_CAP_LET_RECOGNITION,
	ERR_COULDNT_SET_SPELLING,
	ERR_COULDNT_SET_VOICE,
	ERR_COULDNT_SET_TABLE,
	ERR_COULDNT_SET_CLIENT_NAME,
	ERR_COULDNT_SET_OUTPUT_MODULE,
	ERR_COULDNT_SET_PAUSE_CONTEXT,
	ERR_COULDNT_SET_VOLUME,
	ERR_COULDNT_SET_SSML_MODE,
	ERR_COULDNT_SET_NOTIFICATION,
	ERR_COULDNT_SET_DEBUGGING, /* 317 */

	ERR_NO_SOUND_ICONS = 320,
	ERR_MODULE_CANT_REPORT_VOICES,
	ERR_NO_OUTPUT_MODULE_LOADED,	/* 322 */

	ERR_ALREADY_INSIDE_BLOCK = 330,
	ERR_ALREADY_OUTSIDE_BLOCK,
	ERR_NOT_ALLOWED_INSIDE_BLOCK, /* 332 */

	ERR_NOT_YET_IMPLEMENTED = 380,

	ERR_NO_CLIENT = 401,
	ERR_NO_SUCH_CLIENT,
	ERR_NO_MESSAGE,
	ERR_POSITION_TOO_LOW,
	ERR_POSITION_TOO_HIGH,
	ERR_ID_DOESNT_EXIST,
	ERR_UNKNOWN_ICON,
	ERR_UNKNOWN_PRIORITY,
	ERR_RATE_TOO_HIGH,
	ERR_RATE_TOO_LOW,
	ERR_PITCH_TOO_HIGH,
	ERR_PITCH_TOO_LOW,
	ERR_VOLUME_TOO_HIGH,
	ERR_VOLUME_TOO_LOW,   /* 414 */

	ERR_INVALID_COMMAND = 500,
	ERR_INVALID_ENCODING,

	ERR_MISSING_PARAMETER = 510,
	ERR_PARAMETER_NOT_A_NUMBER,
	ERR_PARAMETER_NOT_A_STRING,
	ERR_PARAMETER_NOT_ON_OFF,
	ERR_PARAMETER_INVALID,  /* 514 */

	EVENT_INDEX_MARK = 700,
	EVENT_BEGIN,
	EVENT_END,
	EVENT_CANCELED,
	EVENT_PAUSED,
	EVENT_RESUMED, /* 705 */
} SsipStatus;

G_END_DECLS

#endif /* SSIP_ENUMS_H */
